Q1: Numpy array
1. Write a Python program to create a 5x5 array with random values and find the minimum and
maximum values.
2. Write a Python program to create a random 10x4 array and extract the first five rows of the array
and store them into a variable.
3. Write a Python program to create a random vector of size 10 and sort it.
4. Write a Python program to find the most frequent value in an one-dimensional array

In [2]:
# Q1.1
import numpy as np

arr = np.random.rand(5, 5)

min_val = np.min(arr)
max_val = np.max(arr)

print("Array:")
print(arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

#Q1.2
arr = np.random.rand(10, 4)

first_five_rows = arr[:5, :]

print("Array:")
print(arr)
print("First five rows:")
print(first_five_rows)

#Q1.3
vec = np.random.rand(10)

# Sort the vector
sorted_vec = np.sort(vec)

print("Vector:")
print(vec)
print("Sorted vector:")
print(sorted_vec)

#Q1.4
arr = np.array([1, 2, 3, 4, 1, 2, 3, 1, 2, 1])

# Find the most frequent value
most_freq_val = np.bincount(arr).argmax()

print("Array:")
print(arr)
print("Most frequent value:", most_freq_val)

Array:
[[0.96393374 0.51211201 0.94208078 0.50747857 0.57903664]
 [0.20548241 0.9176142  0.82885849 0.53586256 0.72719432]
 [0.46476348 0.2521272  0.87826644 0.23697573 0.39069737]
 [0.11828694 0.31384893 0.4525365  0.8951974  0.924412  ]
 [0.00544753 0.67413239 0.09491104 0.44955838 0.00686246]]
Minimum value: 0.0054475314119896145
Maximum value: 0.963933741393932
Array:
[[0.60176728 0.57969559 0.63338783 0.6187333 ]
 [0.01825686 0.67263267 0.70113313 0.16644685]
 [0.184251   0.37989715 0.76094664 0.86833172]
 [0.94839683 0.9092024  0.12563433 0.39036858]
 [0.47197551 0.95982715 0.65819468 0.44411767]
 [0.17256578 0.88341814 0.81555171 0.09983088]
 [0.98954834 0.94394961 0.11347603 0.76728404]
 [0.5829379  0.94301153 0.45922371 0.60719934]
 [0.71098498 0.91447879 0.57633919 0.18465263]
 [0.32125531 0.06813123 0.50810724 0.33235486]]
First five rows:
[[0.60176728 0.57969559 0.63338783 0.6187333 ]
 [0.01825686 0.67263267 0.70113313 0.16644685]
 [0.184251   0.37989715 0.76094664 0.868331

Q2. Linear Algebra (40pts)
Bob invested $10,000 on two mutual funds one year ago. After one year, the overall yield rates
for these two mutual funds are +2% and +4%. His yearend account showed $10,250. How much
did he initially put onto two mutual funds? 

Let's represent the initial amount invested in mutual fund 1 by x, and the initial amount invested in mutual fund 2 by y.
So we have the equation: x + y = 10000
After one year, the overall yield rates for these two mutual funds are +2% and +4%. His yearend account showed $10,250.
The amount he earned on the first mutual fund is 0.02x and the amount he earned on the second mutual fund is 0.04y. So, we have the equation: x + y + 0.02x + 0.04y = 10250;
1.02x + 1.04y = 10250
We have this:
x + y = 10000
1.02x + 1.04y = 10250
let's multiplying the first equation by 1.02, we get: 1.02x + 1.02y = 10200, then we get
we get: 0.02y = 50, thus we get y = 2500
for the x we get: x + 2500 = 10000, so, x = 7500. Therefore, Bob put $7500 on one mutual fund and $2500 on the other mutual fund.

Q3. K-means Clustering
Load the data from attached file “Assignment_table.csv”.
• Create a histogram for the first and second column respectively (20 points)
• Conduct a clustering algorithm on these two columns. Try out 3,4,5 clusters respectively.
What do you think is the right number of clusters for this dataset? (40 points)

In [10]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans

# Load data
data = pd.read_csv("Assignment_table.csv")

# Create histograms for first and second columns
plt.hist(data.iloc[:, 0], bins=20)
plt.title("Histogram for Column 1")
plt.xlabel("Column 1 values")
plt.ylabel("Frequency")
plt.show()

plt.hist(data.iloc[:, 1], bins=20)
plt.title("Histogram for Column 2")
plt.xlabel("Column 2 values")
plt.ylabel("Frequency")
plt.show()

# Perform clustering with different number of clusters
X = data.iloc[:, [0, 1]].values

for n_clusters in range(3, 6):
    kmeans = KMeans(n_clusters=n_clusters, random_state=0)
    kmeans.fit(X)
    labels = kmeans.labels_
    centroids = kmeans.cluster_centers_

    # Visualize the results
    plt.scatter(X[:, 0], X[:, 1], c=labels)
    plt.scatter(centroids[:, 0], centroids[:, 1], marker='*', s=300, c='r')
    plt.title(f'K-means Clustering Results (n_clusters={n_clusters})')
    plt.xlabel('Column 1')
    plt.ylabel('Column 2')
    plt.show()


ModuleNotFoundError: No module named 'matplotlib'